### ISSUE TITLE
Erro de renderização

### ISSUE THREAD

**Issue by AldairAvelino** [davigledson/davigledson#3]
Fala dev, beleza!? @davigledson 

Dá uma olhada no teu código, pois ele está tendo erro de renderização

![Capturar](https://github.com/davigledson/davigledson/assets/71715517/b424fb3e-81bd-4a3e-bdb7-dc01c5e594d0)

**Comment by davigledson** [comment]
Fala @AldairAvelino, obrigado ai, 
essa API sempre congestiona de vez em quando mesmo

**Comment by AldairAvelino** [comment]
Sem problemas. @davigledson
